checks:
  addAllBuiltIn: true
  exclude:
  - "host-network"
  - "no-read-only-root-fs"
  - "privilege-escalation-container"
  - "privileged-container"
  - "run-as-non-root"
  - "no-liveness-probe"
  - "no-readiness-probe"
  - "required-annotation-email"
  - "writable-host-mount"
