{{ if .Values.cniConfig }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "name" . }}-config
  namespace: kube-system
  labels:
    tier: node
    {{- include "labels.common" . | nindent 4 }}
data:
  cni-conf.json: |
  {{- .Values.cniConfig | nindent 4 }}
{{ end }}
